### ISSUE TITLE
Speed missing - and name odd default

### ISSUE THREAD

**Issue by dceejay** [zuhito/node-red-contrib-flightradar24#3]
Hi,

Just trying this out - for some reason you are removing the speed value from the output - can it be restored ? or maybe made optional. (I think you have done it to remove the bearing leader lines when shown on map) - but it is useful information. Maybe call it airspeed ? so that it is there but doesn't create the leader unless we add a change node ? 

Also the name often defaults to something odd - I think it would make sense to default the name to the registration - and then finally the modes transponder code . so 
```
msg.payload.name = flight.flight || flight.registration || flight.modeSCode;
```

Thanks

PS - we prefer icons to be white if possible. Not a problem but easy to change the svg fill :-)

**Comment by zuhito** [comment]
Thank you for your suggestions. I updated the node based on your comments.
https://flows.nodered.org/node/node-red-contrib-flightradar24
