### ISSUE TITLE
TypeError: geolib.isPointInCircle is not a function`

### ISSUE THREAD

**Issue by juggledad** [zuhito/node-red-contrib-flightradar24#4]
Running on macOS
Node-RED version: v0.20.8
Node.js  version: v10.15.3
Worldmap version 2.1.0
Dashboard version 2.16.3
node-red-contrib-flightradar24 v0.0.6

I'm getting this error using the node:
`22 Sep 10:25:04 - [error] [flightradar24:5db8cd0e.6b6c0c] TypeError: geolib.isPointInCircle is not a function`
 
Digging in I see that there was a similar issue with the geofence node (https://github.com/hardillb/node-red-node-geofence/issues/14) because a new version of `geolib` (v3.0.x) changes the name of the  `isPointInCircle()` function to `isPointInRadius()` NOTE: that name is wrong the new function is `isPointWithinRadius()`.

Changing the code to use `isPointWithinRadius ` and it works. 

In the geofence issue he changed the version of geolib required.

**Comment by zuhito** [comment]
Thank you for your information. I changed the method name in the commit, https://github.com/zuhito/node-red-contrib-flightradar24/commit/3c2242b686d84a65244e7c169888d25f19a4ea39.

**Comment by dceejay** [comment]
Hmm - now I'm getting `geolib.isPointWithinRadius is not a function` as I have geofence (and another) node that used geolib at `^2.0.0` so your * matches that and npm is ok. Either you need to specify 3.* , or 2.* and drop back to isPointWithinRadius

**Comment by ristomatti** [comment]
... or during init phase test which function is available and call accordingly if this is the only difference between the versions affecting use with this node.

**Comment by zuhito** [comment]
@ristomatti No problem. The latest version of this module doesn't have the fgeolib module as a dependant.
