### ISSUE TITLE
Geolib library still causing issues

### ISSUE THREAD

**Issue by dceejay** [zuhito/node-red-contrib-flightradar24#5]
Hmm - now I'm getting `geolib.isPointWithinRadius is not a function` error as I have geofence (and another) node that used geolib at `^2.0.0` so your * matches that and npm is ok. Either you need to specify `^3.0.0` , or `^2.0.0` and drop back to isPointWithinRadius.

Then again... I'm not quite sure why you are checking a radius - the flightradar request is within a rectangular bounding box anyway - and you are using +/- 1 degree which is about 111km (at the equator) - and given we draw on rectangular screens restricting it to a circular radius may be unnecessary, and would then remove geolib completely...

(I would also pin the flightradar24-client lib version in case they update that behind your back - though it hasn't been touched for two years so less likely...)

**Comment by zuhito** [comment]
@dceejay Thank you for your comment. I removed geolib handling and specified the flightradar24-client version. I also published it as v0.0.8.
https://flows.nodered.org/node/node-red-contrib-flightradar24

**Comment by dceejay** [comment]
Many thanks... much simpler 👍
