### ISSUE TITLE
Not cloning object - can get overwritten

### ISSUE THREAD

**Issue by dceejay** [zuhito/node-red-contrib-flightradar24#7]
Hi,, in the foreach loop- https://github.com/zuhito/node-red-contrib-flightradar24/blob/85d0befcedfb881a557c370ea6e25ac5bcef1e6b/node.js#L22
you aren't cloning the original msg object - so in effect each item in the loop can overwrite the previous one as they are just pointers... you need to clone the original first before adding the new properties, by adding a `var m = RED.util.cloneMessage(msg)` - then adding the properties - then sending that. In the code below I have also set the name to be the callsign as that is more consistent with other public API like opensky, and added a default layer.

```
                data.forEach(function (flight) {
                    var m = RED.util.cloneMessage(msg);
                    m.payload = flight;
                    m.payload.lat = flight.latitude;
                    delete m.payload.latitude;
                    m.payload.lon = flight.longitude;
                    delete m.payload.longitude;
                    m.payload.name = flight.callsign || flight.registration || flight.modeSCode;
                    m.payload.icon = "plane";
                    m.payload.iconColor = "#F9DF39";
                    m.payload.layer = "FlightRadar24";
                    node.send(m);
                });
```

**Comment by dceejay** [comment]
Sight updates to possible fix above.

**Comment by zuhito** [comment]
I updated the node based on suggestion. 
https://flows.nodered.org/node/node-red-contrib-flightradar24
Yellow airplane looks good to distinguish direction and airplane.
Thank you!

**Comment by dceejay** [comment]
Thanks
Well the yellow looks like the version they use on the flightradar24 site so I used their idea :-)
