### ISSUE TITLE
Flight Radar 24 Node stopped working

### ISSUE THREAD

**Issue by FatPilot** [zuhito/node-red-contrib-flightradar24#9]
Flight Radar 24 Node stopped working with an error = "Error: Forbidden".
So I'm guessing that Flight Radar 24 have changed something or blocked it.
Thank you for your contribution.
Paul.

**Comment by tux2000** [comment]
I assume its a change in the API due to the redesign of the FR24 website. Probably needs to be fixed upstream in https://github.com/derhuerst/flightradar24-client

**Comment by jurasjo** [comment]
https://github.com/derhuerst/flightradar24-client/issues/29

**Comment by DeanCording** [comment]
This patch worked for me.  You need to edit flight.js and radar.js

https://github.com/derhuerst/flightradar24-client/issues/29#issuecomment-1620560829

**Comment by FatPilot** [comment]
The patch also worked for me!
Thank you for sorting this out!
I'm really very impressed with this community and it's response.

**Comment by flyturbo** [comment]
Wow, that worked for me as well! Big thank you!!!

**Comment by tux2000** [comment]
Somehow it still doesnt work for me after the updates to flightradar24-client. Any of you using this from within homeassistant?

**Comment by tux2000** [comment]
Got it working yesterday after specifying the 1.0.0 dependency version and updating the import in fr24tube on a forked version of the code here: https://github.com/tux2000/node-red-contrib-fr24tube

Should be possible to fix accordingly in this codebase as well...

**Comment by DeanCording** [comment]
Broken again due to Flight Radar 24 API changes.

See https://github.com/derhuerst/flightradar24-client/issues/36

Workaround mentioned there fixes the issue but uncertain for how long.

**Comment by kazuhitoyokoi** [comment]
Sorry for my late. I updated and published the new node using the latest module.
https://flows.nodered.org/node/node-red-contrib-flightradar24
